site_name: Álgebra Linear e Teoria da Informação

site_dir: build

nav:
  - Home: index.md
  - "Vetores":
    - "Teoria: Uma caminhada por Chicago": vetores/caminhando_pela_cidade.ipynb
    - "Teoria: Propriedades de vetores": vetores/propriedades_soma_e_multiplicacao_escalar.md
    - "Atividade: Ângulos e Distâncias": vetores/angulos.ipynb
    - "Teoria: Vetores e Numpy": vetores/numpy01.ipynb
    - "Teoria: Projeções e produto interno": vetores/projecoes.ipynb
  - "Teoria da Informação":
    - "Compressão Sem Perdas": compressao/compressao_huffman.md
    - "Prática: Compressão Sem Perdas em Áudio": compressao/compressao_sem_perdas_audio.ipynb


theme:
  name: mkdocs
  features:
    - content.mathjax


markdown_extensions:
  - codehilite
  - mdx_math:
      enable_dollar_delimiter: true 
      add_preview: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets



plugins:
  - search
  - mermaid2
  # - mkdocs-jupyter:
  #     ignore_h1_titles: True
  #     theme: mkdocs
  - mknotebooks:
      tag_remove_configs:
        remove_input_tags:
          - remove-input



extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
  # carrega o Mermaid da CDN
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js
